FROM ubuntu:15.04

ADD sources.list.vivid /etc/apt/sources.list

RUN groupadd -g 1000 local; useradd -u 1000 -g 1000 -m local; \
    echo "export TERM=xterm-256color" >> /home/local/.bashrc; \
    chown -R local:local /home/local

RUN apt-get update; apt-get install -y --no-install-recommends ca-certificates wget

ENV proxy=http://172.17.42.1:3128

