FROM tdsparrow/dev-base

USER root

RUN apt-get install -y --no-install-recommends erlang rebar erlang-meck erlang-manpages

USER erenlii

RUN mkdir /home/erenlii/.emacs.d

ADD emacs/emacs-config /home/erenlii/.emacs.d/emacs-config

RUN emacs -batch -l ~/.emacs.d/emacs-config/init.d/init-erlang-packages.el

COPY emacs/.emacs.erlang /home/erenlii/.emacs

USER root

RUN chown -R erenlii:eusers /home/erenlii/.emacs.d/emacs-config /home/erenlii/.emacs


