FROM ubuntu:14.04

ADD sources.list.trusty /etc/apt/sources.list

RUN  apt-get update; apt-get install -y --no-install-recommends software-properties-common; add-apt-repository ppa:ambrop7/badvpn; apt-get update; apt-get install -y badvpn

RUN apt-get install --no-install-recommends -y ipset

ADD cn.zone /root/cn.zone

ENTRYPOINT /usr/bin/fqroute
