FROM ubuntu:14.04

ADD sources.list.trusty /etc/apt/sources.list

RUN apt-get update

RUN apt-get install -y --no-install-recommends make emacs git ca-certificates man

RUN groupadd -g 64000 eusers; useradd -u 11090 -g 64000 -m erenlii

USER erenlii

RUN echo "export TERM=xterm-256color" >> /home/erenlii/.bashrc
