FROM tdsparrow/base:xenial

RUN apt-get update; apt-get install -y --no-install-recommends python python-pip ipython libpq-dev libxml2-dev python-dev libxslt1-dev

RUN pip install --upgrade pip setuptools

RUN pip install jedi virtualenv pylint

ADD zeus_env.yml /etc/eleme/env.yaml
RUN mkdir /data; chmod 777 /data
