FROM tdsparrow/base:vivid

USER root

RUN apt-get update; apt-get install -y --no-install-recommends make emacs git wget man gcc

USER local

RUN cd ~/;  wget https://raw.githubusercontent.com/dimitri/el-get/master/el-get-install.el; emacs --batch -l ~/el-get-install.el

ENV proxy=http://172.17.42.1:8123

RUN  http_proxy=$http https_proxy=$http emacs --batch --eval "(progn (add-to-list 'load-path \"~/.emacs.d/el-get/el-get\") \
                                 (require 'el-get) \
                                 (require 'package) \ 
                                 (add-to-list 'package-archives \
                                            '(\"marmalde\" . \"http://marmalade-repo.org/packages/\") t) \
                                 (add-to-list 'package-archives \
                                              '(\"melpa\" . \"http://melpa.milkbox.net/packages/\") t) \
                                 (add-to-list 'package-archives \
                                             '(\"elpa\" . \"http://elpa.gnu.org/packages/\") t) \
                                 (el-get-elpa-build-local-recipes) \
                                 (dolist (p '(helm monokai-theme highlight-parentheses auto-highlight-symbol)) \
                                     (el-get-bundle-el-get (list :name p :type 'elpa :after nil))) \
                                 (el-get 'sync '(company-mode)))"

RUN ln -s /Sources/emacs-config/.emacs.docker ~/.emacs; ln -s /Sources/emacs-config/init.d ~/.emacs.d/init.d

